name: "Test Renv setup"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: 'renv'
      - name: 📦 Install dependencies with renv
        uses: r-lib/actions/setup-renv@v2-branch
        env:
          RENV_CONFIG_PAK_ENABLED: true
        with:
          cache-version: 2

      - name: Test renv setup
        shell: Rscript {0}
        run: renv::status()

      - name: Test renv setup
        shell: Rscript {0}
        run: source("script.R")
