name: "Update Metadata"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *'

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.DATAFLOWS_WORKFLOW_TOKEN }}
      az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
      az_app_id_pbi_dataset: ${{ secrets.AZ_APP_ID_PBI_DATASET }}
      az_cli_secret_pbi_dataset: ${{ secrets.AZ_CLI_SECRET_PBI_DATASET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      - name: 📦 Install dependencies with renv
        uses: r-lib/actions/setup-renv@v2
        env:
          RENV_CONFIG_PAK_ENABLED: true

      - name: Run script
        run: Rscript update_metadata.R
