name: "Test Renv setup"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: 'renv'
      - uses: r-lib/actions/setup-r-dependencies@v2-branch
      